##################################################################
# Direwolf Instance A
# KISS TCP: 8001   AGW TCP: 8000
# Audio: routed by setup.sh via pactl after launch
##################################################################

ADEVICE  default  default

CHANNEL 0
MYCALL  N0CALL-1
MODEM   1200
TXDELAY 3
TXTAIL  3
PACLEN  240

AGWPORT 8000
KISSPORT 8001
