##################################################################
# Direwolf Instance B
# KISS TCP: 8002   AGW TCP: 8010
# Audio: routed by setup.sh via pactl after launch
##################################################################

ADEVICE  default  default

CHANNEL 0
MYCALL  N0CALL-2
MODEM   1200
TXDELAY 3
TXTAIL  3
PACLEN  240

AGWPORT 8010
KISSPORT 8002
